import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Providers from '@/utils/queryProvider';
import { QueryClient, QueryClientProvider } from 'react-query';
import { UIProviders } from '@/utils/uiProvider';

const inter = Inter({ subsets: ['latin'] })

// export const runtime = 'edge'

export const metadata: Metadata = {
  title: 'Textplay',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  // const client = new QueryClient()
  return (
    <html lang="en">
      <body className={inter.className}>
        <UIProviders>
          <Providers>
              {children}
          </Providers>
        </UIProviders>
      </body>
    </html>
  )
}
